### ISSUE TITLE
Error importing in Typescript ESM project

### ISSUE THREAD

**Issue by lschierer** [adobe/spectrum-css#3061]
## Description

I am getting an error importing the modules in an astro starlight (which uses vite under the hood) project that is configured with ```"type": "module",``` in its package.json.  

```
Error
An error occurred.
Missing "./dist/index.css" specifier in "@spectrum-css/typography" package
Stack Trace
Error: Missing "./dist/index.css" specifier in "@spectrum-css/typography" package
    at e (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:45994:25)
    at n (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:45994:627)
    at o (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:45994:1297)
    at resolveExportsOrImports (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46615:18)
    at resolveDeepImport (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46638:25)
    at tryNodeResolve (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46403:16)
    at ResolveIdContext.resolveId (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46153:19)
    at PluginContainer.resolveId (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48968:17)
    at async ResolveIdContext.resolve (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49128:15)
    at async PluginContainer.resolveId (file:///home/projects/withastro-starlight-dcvzwr/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
```

## Steps to reproduce

I have  a minimal reproduction at https://stackblitz.com/edit/withastro-starlight-dcvzwr?file=package.json

alternately

1.  create a new starlight project with ```pnpm create astro --template starlight```
2. install 
    ```"@spectrum-css/icon": "^7.1.3",
    "@spectrum-css/page": "^8.1.2",
    "@spectrum-css/tokens": "^14.3.1",
    "@spectrum-css/typography": "^6.1.2",
    "@spectrum-css/ui-icons": "^1.1.2",
    "@spectrum-css/vars": "^9.0.8",```
4. edit astro.config.mjs and inside the starlight configuration add ```customCss: [
        '@spectrum-css/tokens/dist/index.css',
        '@spectrum-css/typography/dist/index.css',
        '@spectrum-css/vars/dist/spectrum-global.css',
        '@spectrum-css/vars/dist/spectrum-medium.css',
        '@spectrum-css/page/dist/index.css',
        '@spectrum-css/icon/dist/index.css',
      ],```
5. either run in dev mode with ```pnpm dev``` or attempt to build with ```pnpm build```

## Expected behavior

As I haven't actually *used* the CSS yet with this minimal reproduction, there should be no change to starlight's behavior.  

## Environment

I am using the following versions:

```
"@astrojs/starlight": "^0.26.1",
    "@spectrum-css/icon": "^7.1.3",
    "@spectrum-css/page": "^8.1.2",
    "@spectrum-css/tokens": "^14.3.1",
    "@spectrum-css/typography": "^6.1.2",
    "@spectrum-css/ui-icons": "^1.1.2",
    "@spectrum-css/vars": "^9.0.8",
    "astro": "^4.10.2",
    "sharp": "^0.32.5"
```

I have reproduced this on both OSX and Linux, and with both node v18 and v22. 

## Additional context

<!-- Provide any additional information that might help us debug the issue -->

**Comment by castastrophe** [comment]
Hi @lschierer! Thanks for reaching out with your issue.  I took a look at your reproduction and noted that you're using the latest versions for the components. One thing I noticed is that your imports were including the `dist` directory but our exports are alias'ing that for you to simplify the process.  You should be okay to use:

```
'@spectrum-css/tokens/dist/index.css',
'@spectrum-css/typography/index.css',
'@spectrum-css/page/index.css',
'@spectrum-css/icon/index.css',
```

as these are our exports for each component:

```
"exports": {
  ".": "./dist/index.css",
  "./CHANGELOG.md": "./CHANGELOG.md",
  "./index-*.css": "./dist/index-*.css",
  "./index.css": "./dist/index.css",
  "./metadata.json": "./metadata/metadata.json",
  "./metadata/*": "./metadata/*",
  "./package.json": "./package.json",
  "./stories/*": "./stories/*"
},
```

You also should not need to load the @spectrum-css/vars package as those are legacy tokens and all our current component versions are leveraging the latest @spectrum-css/tokens package.

**Comment by castastrophe** [comment]
We can also include the dist directory exports in a future release to make it even easier to access these assets.  Thanks for sharing with us how you're using our library.

**Comment by lschierer** [comment]
Yes, things are working fine now, thanks :-)
